config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #Path to root page
  root to: 'public#index', as: 'root'
  #User handling routes
  devise_for :users, skip: [:sessions, :passwords, :confirmations, :registrations, :unlocks]
  match 'lang/:locale', to: 'visitors#change_locale', as: :change_locale, via: [:get]
  #Update user profile
  #get '/user/edit', to: 'users/users#edit', as: 'user_edit'  
  put '/user/edit', to: 'users#update', as: 'user_update'
  ###############################################################
  devise_scope :user do
    get '/signin', to: 'users/sessions#new', as: 'new_user_session'
    post '/signin', to: 'users/sessions#create', as: 'user_session'
    get '/signout', to: 'users/sessions#sdestroy', as: 'secure_destroy_user_session'
    delete '/signout', to: 'users/sessions#destroy', as: 'destroy_user_session'
    # registrations
    get '/signup', to: 'users/registrations#new', as: 'new_user_registration'
    post '/signup', to: 'users/registrations#create', as: 'user_registration'
    # user accounts
    scope '/account' do
      # confirmation
      get '/verification', to: 'users/confirmations#verification_sent', as: 'user_verification_sent'
      get '/confirm', to: 'users/confirmations#show', as: 'user_confirmation'
      get '/confirm/resend', to: 'users/confirmations#new', as: 'new_user_confirmation'
      post '/confirm', to: 'users/confirmations#create'
      # passwords
      get '/reset-password', to: 'users/passwords#new', as: 'new_user_password'
      get '/reset-password/change', to: 'users/passwords#edit', as: 'edit_user_password'
      put  '/reset-password', to: 'users/passwords#update', as: 'user_password'
      post '/reset-password', to: 'users/passwords#create'
      # unlocks
      post '/unlock', to: 'users/unlocks#create', as: 'user_unlock'
      get '/unlock/new', to: 'users/unlocks#new', as: 'new_user_unlock'
      get '/unlock', to: 'users/unlocks#show'
      # settings & cancellation
      get '/cancel', to: 'users/registrations#cancel', as: 'cancel_user_registration'
      get '/settings', to: 'users/registrations#edit', as: 'edit_user_registration'
      put '/settings', to: 'users/registrations#update', as: 'update_user_registration'
      # account deletion
      delete '/delete', to: 'users/registrations#destroy', as: 'destroy_user_registration'
    end
  end
  #User account paths
  get '/account', to: 'users#account', as: 'account'
  get '/account/edit_news', to: 'users/contents#edit_news'
  put '/account/update_news', to: 'users/contents#update_news'
  ################################################################
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth',
                                  controllers: {
                                      sessions: 'api/v1/devise_token_auth/sessions',
                                      registrations: 'api/v1/devise_token_auth/registrations'
                                  }
      resources :devices, only: [ :create ]
      resources :locations, only: [ :create ]
      post '/analyze', to: 'alpr#analyze', as: 'alpr_analyze'
    end
  end
  #samples index path
  get '/samples', to: 'users/samples#index', as: 'samples'
  scope :users do
    #User sample new path
    get '/sample/new', to: 'users/samples#new', as: 'sample_new'
    post '/sample/new', to: 'users/samples#create', as: 'sample_create'
    #user sample edit & delete path
    resources :samples, only:[] do
      #User samples update and destroy paths
      get '/edit', to: 'users/samples#edit', as: 'edit'
      put '/edit', to: 'users/samples#update', as: 'update'
      delete '/delete', to: 'users/samples#destroy', as: 'destroy'
    end
  end
end

app/models/sample.rb
class Sample < ApplicationRecord
  belongs_to :user

  # Backend validations
  validates :error_name,
            :presence => true
  validates :description,
            :presence => true

  def error_name
    if self.name.nil?
      errors.add(:name, "Please enter the name of the object.")
    end
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApiController
  before_action :authenticate_user!


  #Upgrading user profile and giving driver/business roles
  def upgrade(param)

    if param == "driver"
      @driver = Driver.new(driver_params)
      @driver.user_id = @current_user.id
      respond_to do |format|
        if @driver.save
          format.html { redirect_to account_path, notice: 'driver was successfully created.' }
          format.json { render :show, status: :created, location: @driver }
          @current_user.driver!
        else
          redirect_back_or_default(root_path, :alert => "Something went wrong!.")
        end
      end
    elsif param == "business"
      @business = Business.new(business_params)
      @business.user_id = @current_user.id
      respond_to do |format|
        if @business.save
          format.html { redirect_to business_path, notice: 'business was successfully created.' }
          format.json { render :show, status: :created, location: @business }
          @current_user.business!
        else
          format.html { render :new }
          format.json { render json: @business.errors, status: :unprocessable_entity }
        end
      end
    else
        flash[:notice] = "Bad role!"
    end
  end





  # Only allow a trusted parameter "white list" through.
  def driver_params
    if Rails::VERSION::MAJOR < 4
      params[:driver].permit(:_destroy)
    else
      protected_attrs =  ["created_at", "updated_at"]
      params.require(:driver).permit(Driver.new.attributes.keys - protected_attrs, :_destroy)
    end
  end


  # Only allow a trusted parameter "white list" through.
  def business_params
    if Rails::VERSION::MAJOR < 4
      params[:business].permit(:_destroy)
    else
      protected_attrs =  ["created_at", "updated_at"]
      params.require(:business).permit(Business.new.attributes.keys - protected_attrs, :_destroy)
    end
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  def new
    self.resource = resource_class.new
  end

  # POST /resource/confirmation
  def create
    self.resource = resource_class.send_confirmation_instructions(resource_params)
    yield resource if block_given?

    if successfully_sent?(resource)
      respond_with({}, location: after_resending_confirmation_instructions_path_for(resource_name))
    else
      respond_with(resource)
    end
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    self.resource = resource_class.confirm_by_token(params[:confirmation_token])
    yield resource if block_given?

    if resource.errors.empty?
      set_flash_message!(:success, :confirmed)
      respond_with_navigational(resource){ redirect_to after_confirmation_path_for(resource_name, resource) }
    else
      respond_with_navigational(resource.errors, status: :unprocessable_entity){ render :new }
    end
  end

  protected

  # The path used after resending confirmation instructions.
  def after_resending_confirmation_instructions_path_for(resource_name)
    is_navigational_format? ? new_session_path(resource_name) : '/'
  end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    if signed_in?(resource_name)
      signed_in_root_path(resource)
    else
      new_session_path(resource_name)
    end
  end

  def translation_scope
    'devise.confirmations'
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  prepend_before_action { request.env["devise.skip_timeout"] = true }

  def passthru
    render status: 404, text: "Not found. Authentication passthru."
  end

  def failure
    set_flash_message :danger, :failure, kind: OmniAuth::Utils.camelize(failed_strategy.name), reason: failure_message
    redirect_to after_omniauth_failure_path_for(resource_name)
  end

  protected

  def failed_strategy
    request.respond_to?(:get_header) ? request.get_header("omniauth.error.strategy") : request.env["omniauth.error.strategy"]
  end

  def failure_message
    exception = request.respond_to?(:get_header) ? request.get_header("omniauth.error") : request.env["omniauth.error"]
    error   = exception.error_reason if exception.respond_to?(:error_reason)
    error ||= exception.error        if exception.respond_to?(:error)
    error ||= (request.respond_to?(:get_header) ? request.get_header("omniauth.error.type") : request.env["omniauth.error.type"]).to_s
    error.to_s.humanize if error
  end

  def after_omniauth_failure_path_for(scope)
    new_session_path(scope)
  end

  def translation_scope
    'devise.omniauth_callbacks'
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController

  prepend_before_action :require_no_authentication
  # Render the #edit only if coming from a reset password email link
  append_before_action :assert_reset_token_passed, only: :edit

  # GET /resource/password/new
  def new
    @header_title = t('users.passwords.new.header_title')
    self.resource = resource_class.new
  end

  # POST /resource/password
  def create

    self.resource = resource_class.send_reset_password_instructions(resource_params)
    yield resource if block_given?

    if successfully_sent?(resource)
      respond_with({}, location: after_sending_reset_password_instructions_path_for(resource_name))
    else
      respond_with(resource)
    end
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    @header_title = t('users.passwords.edit.header_title')
    self.resource = resource_class.new
    set_minimum_password_length
    resource.reset_password_token = params[:reset_password_token]
  end

  # PUT /resource/password
  def update
    self.resource = resource_class.reset_password_by_token(resource_params)
    yield resource if block_given?

    if resource.errors.empty?
      resource.unlock_access! if unlockable?(resource)
      if Devise.sign_in_after_reset_password
        flash_message = resource.active_for_authentication? ? :updated : :updated_not_active
        set_flash_message!(:success, flash_message)
        sign_in(resource_name, resource)
      else
        set_flash_message!(:danger, :updated_not_active)
      end
      respond_with resource, location: after_resetting_password_path_for(resource)
    else
      set_minimum_password_length
      respond_with resource
    end
  end

  protected
  def after_resetting_password_path_for(resource)
    Devise.sign_in_after_reset_password ? after_sign_in_path_for(resource) : new_session_path(resource_name)
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    new_session_path(resource_name) if is_navigational_format?
  end

  # Check if a reset_password_token is provided in the request
  def assert_reset_token_passed
    if params[:reset_password_token].blank?
      set_flash_message(:danger, :no_token)
      redirect_to new_session_path(resource_name)
    end
  end

  # Check if proper Lockable module methods are present & unlock strategy
  # allows to unlock resource on password reset
  def unlockable?(resource)
    resource.respond_to?(:unlock_access!) &&
        resource.respond_to?(:unlock_strategy_enabled?) &&
        resource.unlock_strategy_enabled?(:email)
  end

  def translation_scope
    'devise.passwords'
  end

  # Helper for use after calling send_*_instructions methods on a resource.
  # If we are in paranoid mode, we always act as if the resource was valid
  # and instructions were sent.
  def successfully_sent?(resource)
    notice = if Devise.paranoid
               resource.errors.clear
               :send_paranoid_instructions
             elsif resource.errors.empty?
               :send_instructions
             end

    if notice
      set_flash_message! :warning, notice
      true
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  prepend_before_action :require_no_authentication, only: [:new, :create, :cancel]
  prepend_before_action :authenticate_scope!, only: [:edit, :update, :destroy]
  prepend_before_action :set_minimum_password_length, only: [:new, :edit]

  # GET /resource/sign_up
  def new
    build_resource
    yield resource if block_given?
    respond_with resource
  end

  # POST /resource
  def create
    build_resource(sign_up_params)

    resource.save
    if resource.respond_to?(:unconfirmed_email)
      resource.send_confirmation_instructions(sign_up_params)
    end
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :success, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  # GET /resource/edit
  def edit
    render :edit
  end

  # PUT /resource
  # We need to use a copy of the resource because we don't want to change
  # the current user in place.
  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)

    resource_updated = update_resource(resource, account_update_params)
    yield resource if block_given?
    if resource_updated
      set_flash_message_for_update(resource, prev_unconfirmed_email)
      bypass_sign_in resource, scope: resource_name if sign_in_after_change_password?

      respond_with resource, location: after_update_path_for(resource)
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  # DELETE /resource
  def destroy
    resource.destroy
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    set_flash_message! :notice, :destroyed
    yield resource if block_given?
    respond_with_navigational(resource){ redirect_to after_sign_out_path_for(resource_name) }
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    expire_data_after_sign_in!
    redirect_to new_registration_path(resource_name)
  end

  protected

  def update_needs_confirmation?(resource, previous)
    resource.respond_to?(:pending_reconfirmation?) &&
        resource.pending_reconfirmation? &&
        previous != resource.unconfirmed_email
  end

  # By default we want to require a password checks on update.
  # You can overwrite this method in your own RegistrationsController.
  def update_resource(resource, params)
    resource.update_with_password(params)
  end

  # Build a devise resource passing in the session. Useful to move
  # temporary session data to the newly created user.
  def build_resource(hash = {})
    self.resource = resource_class.new_with_session(hash, session)
  end

  # Signs in a user on sign up. You can overwrite this method in your own
  # RegistrationsController.
  def sign_up(resource_name, resource)
    sign_in(resource_name, resource)
  end

  # The path used after sign up. You need to overwrite this method
  # in your own RegistrationsController.
  def after_sign_up_path_for(resource)
    after_sign_in_path_for(resource) if is_navigational_format?
  end

  # The path used after sign up for inactive accounts. You need to overwrite
  # this method in your own RegistrationsController.
  def after_inactive_sign_up_path_for(resource)
    scope = Devise::Mapping.find_scope!(resource)
    router_name = Devise.mappings[scope].router_name
    context = router_name ? send(router_name) : self
    context.respond_to?(:root_path) ? context.root_path : "/"
  end

  # The default url to be used after updating a resource. You need to overwrite
  # this method in your own RegistrationsController.
  def after_update_path_for(resource)
    sign_in_after_change_password? ? signed_in_root_path(resource) : new_session_path(resource_name)
  end

  # Authenticates the current scope and gets the current resource from the session.
  def authenticate_scope!
    send(:"authenticate_#{resource_name}!", force: true)
    self.resource = send(:"current_#{resource_name}")
  end

  def sign_up_params
    devise_parameter_sanitizer.sanitize(:sign_up)
  end

  def account_update_params
    devise_parameter_sanitizer.sanitize(:account_update)
  end

  def translation_scope
    'devise.registrations'
  end

  private

  def set_flash_message_for_update(resource, prev_unconfirmed_email)
    return unless is_flashing_format?

    flash_key = if update_needs_confirmation?(resource, prev_unconfirmed_email)
                  :update_needs_confirmation
                elsif sign_in_after_change_password?
                  :updated
                else
                  :updated_but_not_signed_in
                end
    set_flash_message :notice, flash_key
  end

  def sign_in_after_change_password?
    return true if account_update_params[:password].blank?

    Devise.sign_in_after_change_password
  end

end

app/views/users/samples/_form.html.erb
<% if current_page?(action: 'new')|| @sample.id.nil? %>
  <%= simple_form_for(@sample, :url => sample_new_path(@sample),
                      :html => { :class => 'form-group directFileUpload custom-form',
                                 :role => 'form'}) do |f| %>
    <div class="col-md-8 col-md-offset-2 request-fields">
      <div class="col-md-12 form-group">
        <%= f.label t("global.name") %>
        <%= f.text_field :name, :class => 'form-control',
                         :"data-fv-notempty"=>"true",
                         :"data-fv-notempty-message"=>"Please enter a sample name."  %>
        <%= f.label t("global.description") %>
        <%= f.input :description, label: false %>
        <%= f.label t("users.samples.form.price") %>
        <%= f.input :price, :class => 'form-control', label: false %>
        <%= f.label t("users.samples.form.quantity") %>
        <%= f.input :quantity, :class => 'form-control', :input_html => {:type => 'number'} , :label => false %>
      </div>
      <div class="col-md-12 form-group">
        <div class="fileinput-image">
          <% unless @sample.image_url.nil? %>
            <img src="<%= @sample.image_url %>" style="width:250px; height:250px" >
          <% else %>
            <h5><%= t("global.no_image") %></h5>
          <% end %>
        </div>
        <span class="btn btn-success fileinput-button">
        <!-- Change based on action -->
          <% if current_page?(action: 'new')|| @sample.image_url.nil? %>
          <span>
            <%= t("global.image") %>
          </span>
        <% else %>
          <span>
            <%= t("global.change_image") %>
          </span>
        <% end %>
          <%= f.file_field :image_url, accept: '*', data: { 'resource-name' => 'image'} %>
      </span>
      </div>
    </div>
    <div class="col-md-8 col-md-offset-2 d-flex justify-content-center">
      <%= f.button :submit, t("global.create"), :class => 'btn btn-primary' %>
    </div>
  <% end %>
<% else %>
  <%= simple_form_for(@sample, :url => sample_update_path(@sample), :method => 'put',
                      :html => { :class => 'form-group directFileUpload custom-form',
                                 :role => 'form'}) do |f| %>
    <div class="col-md-8 col-md-offset-2 request-fields">
      <div class="col-md-12 form-group">
        <%= f.label t("global.name") %>
        <%= f.text_field :name, :class => 'form-control',
                         :"data-fv-notempty"=>"true",
                         :"data-fv-notempty-message"=>"Please enter a sample name."  %>
        <%= f.label t("global.description") %>
        <%= f.input :description, label: false%>
        <%= f.label t("users.samples.form.price") %>
        <%= f.input :price, :class => 'form-control', label: false %>
        <%= f.label t("users.samples.form.quantity") %>
        <%= f.input :quantity, :class => 'form-control', :input_html => {:type => 'number'} , :label => false %>
      </div>
      <div class="col-md-12 form-group">
        <div class="fileinput-image">
          <% unless @sample.image_url.nil? %>
            <img src="<%= @sample.image_url %>" style="width:250px; height:250px" >
          <% else %>
            <h5><%= t("global.no_image") %></h5>
          <% end %>
        </div>
        <span class="btn btn-success fileinput-button">
        <!-- Change based on action -->
          <% if current_page?(action: 'new')|| @sample.image_url.nil? %>
          <span>
            <%= t("global.image") %>
          </span>
        <% else %>
          <span>
            <%= t("global.change_image") %>
          </span>
        <% end %>
          <%= f.file_field :image_url, accept: '*', data: { 'resource-name' => 'image'} %>
      </span>
      </div>
    </div>
    <div class="col-md-8 col-md-offset-2 d-flex justify-content-center">
      <%= f.button :submit, t("global.save"), :class => 'btn btn-primary' %>
    </div>
  <% end %>
<% end %>

<!-- JavaScript code -->
<script>
    $(document).ready(function(){
        InitFileUpload();
    });
</script>

app/views/users/samples/edit.html.erb
<!-- Page Content -->
<div class="container fluid">
  <div class="card border-0 shadow my-5">
    <div class="card-body">
      <h1 class="text-center form-title"><%= t("users.vehicles.edit.title") %></h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/samples/index.html.erb
<!-- Page Content -->
<div class="container fluid">
  <div class="card border-0 shadow my-5">
    <div class="card-body">
      <h2 class="text-center" style="margin-top: 20px; margin-bottom: 20px;"><%= t("global.list") %></h2>
      <table class="table">
        <thead class="thead-dark" >
        <tr>
          <th scope="col"><%= t("global.name") %></th>
          <th scope="col"><%= t("global.description") %></th>
          <th scope="col"><%= t("users.samples.form.price") %></th>
          <th scope="col"><%= t("users.samples.form.quantity") %></th>
          <th scope="col"><%= t("global.delete") %>/<%= t("global.edit") %></th>
        </tr>
        </thead>
        <tbody>
        <% @samples.each do |sample|%>
          <tr>
            <td><%= sample.name%></td>
            <td><%= sample.description%></td>
            <td><%= sample.price%></td>
            <td><%= sample.quantity%></td>
            <td><%= link_to t("global.delete"), sample_destroy_path(sample),:method => :delete %>/<%= link_to t("global.edit"), sample_edit_path(sample) %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <div class="d-flex justify-content-center" style="margin-bottom: 40px;">
        <%= link_to t("global.create"), sample_new_path, :class => 'btn btn-primary '%>
      </div>
    </div>
  </div>
</div>

app/views/users/samples/new.html.erb
<!-- Page Content -->
<div class="container fluid">
  <div class="card border-0 shadow my-5">
    <div class="card-body">
      <h1 class="text-center form-title"><%= t("global.new") %> <%= t("global.object") %></h1>
      <%= render 'form' %>
    </div>
  </div>
</div>