config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #Path to root page
  root to: 'public#index', as: 'root'
  #User handling routes
  devise_for :users, skip: [:sessions, :passwords, :confirmations, :registrations, :unlocks]
  match 'lang/:locale', to: 'visitors#change_locale', as: :change_locale, via: [:get]
  #Update user profile
  #get '/user/edit', to: 'users/users#edit', as: 'user_edit'  
  put '/user/edit', to: 'users#update', as: 'user_update'
  ###############################################################
  devise_scope :user do
    get '/signin', to: 'users/sessions#new', as: 'new_user_session'
    post '/signin', to: 'users/sessions#create', as: 'user_session'
    get '/signout', to: 'users/sessions#sdestroy', as: 'secure_destroy_user_session'
    delete '/signout', to: 'users/sessions#destroy', as: 'destroy_user_session'
    # registrations
    get '/signup', to: 'users/registrations#new', as: 'new_user_registration'
    post '/signup', to: 'users/registrations#create', as: 'user_registration'
    # user accounts
    scope '/account' do
      # confirmation
      get '/verification', to: 'users/confirmations#verification_sent', as: 'user_verification_sent'
      get '/confirm', to: 'users/confirmations#show', as: 'user_confirmation'
      get '/confirm/resend', to: 'users/confirmations#new', as: 'new_user_confirmation'
      post '/confirm', to: 'users/confirmations#create'
      # passwords
      get '/reset-password', to: 'users/passwords#new', as: 'new_user_password'
      get '/reset-password/change', to: 'users/passwords#edit', as: 'edit_user_password'
      put  '/reset-password', to: 'users/passwords#update', as: 'user_password'
      post '/reset-password', to: 'users/passwords#create'
      # unlocks
      post '/unlock', to: 'users/unlocks#create', as: 'user_unlock'
      get '/unlock/new', to: 'users/unlocks#new', as: 'new_user_unlock'
      get '/unlock', to: 'users/unlocks#show'
      # settings & cancellation
      get '/cancel', to: 'users/registrations#cancel', as: 'cancel_user_registration'
      get '/settings', to: 'users/registrations#edit', as: 'edit_user_registration'
      put '/settings', to: 'users/registrations#update', as: 'update_user_registration'
      # account deletion
      delete '/delete', to: 'users/registrations#destroy', as: 'destroy_user_registration'
    end
  end
  #User account paths
  get '/account', to: 'users#account', as: 'account'
  get '/account/edit_news', to: 'users/contents#edit_news'
  put '/account/update_news', to: 'users/contents#update_news'
  ################################################################
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth',
                                  controllers: {
                                      sessions: 'api/v1/devise_token_auth/sessions',
                                      registrations: 'api/v1/devise_token_auth/registrations'
                                  }
      resources :devices, only: [ :create ]
      resources :locations, only: [ :create ]
      post '/analyze', to: 'alpr#analyze', as: 'alpr_analyze'
    end
  end
  #samples index path
  get '/samples', to: 'users/samples#index', as: 'samples'
  scope :users do
    #User sample new path
    get '/sample/new', to: 'users/samples#new', as: 'sample_new'
    post '/sample/new', to: 'users/samples#create', as: 'sample_create'
    #user sample edit & delete path
    resources :samples, only:[] do
      #User samples update and destroy paths
      get '/edit', to: 'users/samples#edit', as: 'edit'
      put '/edit', to: 'users/samples#update', as: 'update'
      delete '/delete', to: 'users/samples#destroy', as: 'destroy'
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="mainfooter" role="contentinfo">
    <div class="footer-middle">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-6 text-center">
                    <!--Column1-->
                    <div class="footer-pad">
                        <h4><%= t("layouts.footer.footer-header-address") %></h4>
                        <address>
                            <ul class="list-unstyled">
                                <li>
                                  <%= t("layouts.footer.footer-city") %><br>
                                  <%= t("layouts.footer.footer-street") %><br>
                                </li>
                            </ul>
                        </address>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6 text-center">
                    <!--Column1-->
                    <div class="footer-pad">
                        <h4><%= t("layouts.footer.footer-header-services") %></h4>
                        <ul class="list-unstyled">
                            <li><a href="#"><%= t("layouts.footer.footer-header-alpr") %></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6 text-center">
                    <!--Column1-->
                    <div class="footer-pad">
                        <h4><%= t("layouts.footer.footer-expo-link") %></h4>
                        <ul class="list-unstyled">
                            <li>
                              <a href="https://play.google.com/store/apps/details?id=host.exp.exponent&referrer=www">Expo Android</a>
                            </li>
                            <li>
                              <a href="https://itunes.apple.com/app/apple-store/id982107779">Expo IOS</a>
                            </li>
                            <li>
                              <a href="https://expo.io/@dkperson/nativeapp">Plate Vision</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6 text-center">
                    <!--Column1-->
                    <div class="footer-pad">
                        <h4 >QR Code</h4>
                        <img src="https://i.imgur.com/jFTRmaT.png" width="100" height="100">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <!--Footer Bottom-->
                    <p class=text-center>&copy; <%= t("layouts.footer.footer-text") %></p>
                </div>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_languages_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="langModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title">Languages</h2>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" style="padding: 0 !important;">
        <ul class="langList">
          <% I18n.available_locales.each do |lang| %>
            <li>
              <%= link_to t(lang), change_locale_path(lang) %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="navbar-title">
      <a class="navbar-brand" href="<%= root_path %>">Master Rails</a>
    </div>
    <button class="navbar-toggler" type="button"
            data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <!-- Main navigation -->
      <%= render_navigation :expand_all => true, :context => :main %>
      <!-- End main navigation -->
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
  <head>
    <meta charset="utf-8" />
    <meta name="author" content="Master Rails" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%# Application CSS & JS and all includes %>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%# Meta Data %>
    <%= csrf_meta_tags %>
    <title><%= content_for?(:title) ? yield(:title) : "Master_Rails" %></title>
  </head>
  <body class="stretched sticky-responsive-menu">
    <%# Main  navigation content %>
    <%= render 'layouts/navigation' %>
    <%# Languages Modal Popup %>
    <%= render 'layouts/languages_modal' %>
    <% if flash[:notice] %>
      <div class="notice alert alert-success alert-dismissible fade show" role="alert">
        <%= flash[:notice] %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <%# Main page content %>
    <%= yield %>
    <%# Main footer content %>
    <%= render 'layouts/footer' %>
  </body>
</html>